import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CounterStoreProvider from "../../providers/CounterNextjsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Counter application using zustand",
  description: "Generated by create next app ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}
        <CounterStoreProvider>{children}</CounterStoreProvider>
      </body>
    </html>
  );
}
